spring:
  devtools:
    restart:
      additional-exclude: dev/hilla/openapi.json

  # Database
  datasource:
    url: jdbc:postgresql://localhost:5434/vector_store
    username: postgres
    password: postgres

  # Spring AI
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          functions : paymentStatus
          model: gpt-4

    mistralai:
      api-key: ${MISTRAL_AI_API_KEY}
      chat:
        options:
          model: mistral-large-latest

    vectorstore:
      pgvector:
        dimensions: 1536

vaadin:
  launch-browser: true
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,fr.sciam.SpringAiDemo